### ISSUE TITLE
Add a Prettier pre-commit hook.

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/catchup#20]
- Add prettier as a dev dependency.
- Use `npx prettier <config_here>`
- Use [`husky`](https://www.npmjs.com/package/husky) to make Git Hooks easier.

**Comment by KMK-Git** [comment]
Hi, this seems like a simple change, I will take this up since no one else is working on it.

I have one question though, which exact version of prettier should be added in dev dependencies? (https://prettier.io/docs/en/install.html#summary suggests using an exact version to avoid formatting differences) Should I just use the latest version available right now?

I also haven't ran prettier on the existing code, if there are any changes required will add another comment here.

**Comment by KMK-Git** [comment]
https://github.com/KMK-Git/catchup/commit/6b368cea52deb58d4291979bf771a29462c9d7d7

Formatting changes with prettier 2.7.1
